# docker-compose run --rm ourshop-fe-test
version: '3.9'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app