# docker-compose run --rm ourshop-fe-test
version: "3.9"
services:
  yarn-test:
    profiles:
      - test
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    stdin_open: true
    tty: true
