name: Build and deploy uat to Azure Web App

on:
  workflow_run:
    workflows: ['OurShop Unit test']
    types: [completed]
    branches: [ 'uat' ]

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: uat

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ourshop-uat'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_OURSHOP_FE_UAT }}
          package: '.'
